samples:
  - target: 'hg38'
    query: 'panTro6'
    ffrom: 'query'
    outgroup: 'rheMac10'
  - target: 'hg38'
    query: 'panPan3'
    ffrom: 'query'
    outgroup: 'rheMac10'
  - target: 'hg38'
    query: 'gorGor6'
    ffrom: 'query'
    outgroup: 'rheMac10'
  - target: 'hg38'
    query: 'gorGor6'
    ffrom: 'query'
    outgroup: 'rheMac10'
  - target: 'hg38'
    query: 'ponAbe3'
    ffrom: 'query'
    outgroup: 'rheMac10'
  - target: 'hg38'
    query: 'nomLeu3'
    ffrom: 'query'
    outgroup: 'rheMac10'  
