QUALITY_WINDOW_LENGTH = 5
MAX_NUMBER_OF_MISMACHES = 5
CLUSTERED_SUBSTITUTIONS_WINDOW_LENGTH = 300
CLUSTERED_SUBSTITUTIONS_MIN_SIZE = 5
WTS_MIN_PERCENT = 0.8
STW_MAX_PERCENT = 1 - WTS_MIN_PERCENT

WEAK_NUCLEOTIDES = ['A', 'T']
STRONG_NUCLEOTIDES = ['G', 'C']

